# Define content for the .gitignore file
gitignore_content <- "
# Ignore R-related files

*.Rproj.user
.Rhistory
.RData

*.Rproj

# Ignore backup files
*~

# Ignore hidden files
.*

# Ignore environment files
.Renviron
.Rprofile

# Ignore package documentation in 'man' directory
/man/

# Ignore 'packrat' directory
packrat/

# Ignore files generated by R Markdown
*.html
*.pdf

# Ignore R workspace files
.RData
.RData.*

# Ignore macOS .DS_Store files
.DS_Store

# Ignore Microsoft Word documents
*.docx


# Ignore data files
*.xlsx
*.csv
"

# Write content to .gitignore file
cat(gitignore_content, file = ".gitignore")

# Print a message indicating the file creation
cat(".gitignore file created successfully.\n")
